// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Release struct {
	ID        int64
	Name      string
	SongCount int64
	UserID    string
	Url       string
}

type User struct {
	ID        interface{}
	Username  sql.NullString
	Email     string
	CreatedAt string
	UpdatedAt string
}
