// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: releases.sql

package database

import (
	"context"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (
  name,
  user_id,
  url,
  imgUrl,
  is_public,
  is_single
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, name, user_id, url, imgurl, song_count, is_public, is_single
`

type CreateReleaseParams struct {
	Name     string
	UserID   string
	Url      string
	Imgurl   string
	IsPublic bool
	IsSingle bool
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, createRelease,
		arg.Name,
		arg.UserID,
		arg.Url,
		arg.Imgurl,
		arg.IsPublic,
		arg.IsSingle,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Url,
		&i.Imgurl,
		&i.SongCount,
		&i.IsPublic,
		&i.IsSingle,
	)
	return i, err
}
