// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: releases.sql

package database

import (
	"context"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (
  name,
  user_id,
  url,
  imgUrl,
  is_public
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
)
RETURNING id, name, user_id, url, imgurl, song_count, is_public, created_at, updated_at
`

type CreateReleaseParams struct {
	Name     string
	UserID   string
	Url      string
	Imgurl   string
	IsPublic bool
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, createRelease,
		arg.Name,
		arg.UserID,
		arg.Url,
		arg.Imgurl,
		arg.IsPublic,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Url,
		&i.Imgurl,
		&i.SongCount,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReleaseById = `-- name: DeleteReleaseById :exec
DELETE FROM releases WHERE id = ?
`

func (q *Queries) DeleteReleaseById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseById, id)
	return err
}

const getAllPublicReleases = `-- name: GetAllPublicReleases :many
SELECT id, name, user_id, url, imgurl, song_count, is_public, created_at, updated_at FROM releases WHERE is_public = TRUE
`

func (q *Queries) GetAllPublicReleases(ctx context.Context) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, getAllPublicReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Url,
			&i.Imgurl,
			&i.SongCount,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPublicReleasesByUser = `-- name: GetAllPublicReleasesByUser :many
SELECT id, name, user_id, url, imgurl, song_count, is_public, created_at, updated_at FROM releases WHERE is_public = TRUE AND user_id = ?
`

func (q *Queries) GetAllPublicReleasesByUser(ctx context.Context, userID string) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, getAllPublicReleasesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Url,
			&i.Imgurl,
			&i.SongCount,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllReleasesByUser = `-- name: GetAllReleasesByUser :many
SELECT id, name, user_id, url, imgurl, song_count, is_public, created_at, updated_at FROM releases WHERE user_id = ?
`

func (q *Queries) GetAllReleasesByUser(ctx context.Context, userID string) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, getAllReleasesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Url,
			&i.Imgurl,
			&i.SongCount,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseById = `-- name: GetReleaseById :one
SELECT id, name, user_id, url, imgurl, song_count, is_public, created_at, updated_at FROM releases WHERE id = ?
`

func (q *Queries) GetReleaseById(ctx context.Context, id int64) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseById, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Url,
		&i.Imgurl,
		&i.SongCount,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRelease = `-- name: UpdateRelease :one
UPDATE releases
  SET name = ?,
    url = ?,
    imgUrl = ?,
    is_public = ?,
    updated_at = CURRENT_TIMESTAMP
  WHERE id = ?
RETURNING id, name, user_id, url, imgurl, song_count, is_public, created_at, updated_at
`

type UpdateReleaseParams struct {
	Name     string
	Url      string
	Imgurl   string
	IsPublic bool
	ID       int64
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, updateRelease,
		arg.Name,
		arg.Url,
		arg.Imgurl,
		arg.IsPublic,
		arg.ID,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Url,
		&i.Imgurl,
		&i.SongCount,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
