-- +goose Up
CREATE TABLE users (
  id TEXT PRIMARY KEY DEFAULT (uuid4()) NOT NULL,
  username TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE `users`;
